import { APP_DEFS, CORE_APP_COUNT, FIDELITY_LABELS, PERCUSSION_VOICES } from '../core/reference-catalog.js';
import { currentApp } from '../core/state.js';

const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const selected = condition => condition ? ' selected' : '';
const active = condition => condition ? ' active' : '';
const button = (label, action, extra='') => `<button ${extra} data-action="${action}" data-interactive="1">${label}</button>`;

function appOrdinal(state, app) {
  const index = APP_DEFS.findIndex(item => item.id === app.id);
  return index < CORE_APP_COUNT ? `${index + 1}/${CORE_APP_COUNT}` : `LAB ${index - CORE_APP_COUNT + 1}/${APP_DEFS.length - CORE_APP_COUNT}`;
}
function header(state, platform) {
  const app = currentApp(state);
  return `<header class="topbar accent-${app.accent}" data-action="apps" data-interactive="1"><div class="top-left"><span class="top-title">${esc(app.short)}</span><span class="fidelity fidelity-${app.fidelity.toLowerCase()}" title="${esc(FIDELITY_LABELS[app.fidelity])}">${app.fidelity}</span></div><div class="top-right"><span class="env-pill">${esc(platform.environmentLabel())}</span><span>${appOrdinal(state, app)}</span></div></header>`;
}
function primaryLabel(state) {
  const id = currentApp(state).id;
  return ({rain:state.rain.running?'PAUSE':'RUN',hsv:'SAMPLE',aem:state.aem.degas?'STOP DEGAS':'DEGAS',synth:state.synth.active?'PLAYING':'PLAY',percussion:state.percussion.playing?'STOP':'PLAY',recorder:state.recorder.state==='recording'?'STOP':state.recorder.hasClip?'PLAY':'RECORD',udaq:state.udaq.running?'PAUSE':'RUN',settings:'NEXT PAGE',transfer:state.transfer.unlocked?'HOME':'UNLOCK',communications:state.communications.unlocked?'HOME':'UNLOCK',whofi:state.whofi.running?'STOP CSI':'START CSI',lilmidi:'SCENE',particles:state.particles.paused?'RESUME':'PAUSE',notebook:'SELECT',power:'REFRESH',camera:state.camera.state==='live'?'STOP':'START'})[id] || 'ACTION';
}
function footer(state) {
  const focus = state.interaction?.wheelLabel ? `<span class="wheel-readout">WHEEL ${esc(state.interaction.wheelLabel)}</span>` : '';
  return `<footer class="action-rail"><button class="rail-button" data-action="apps" data-interactive="1">APPS</button><button class="rail-button primary" data-action="primary" data-interactive="1">${esc(primaryLabel(state))}</button><button class="rail-button" data-action="next" data-interactive="1">NEXT</button>${focus}</footer>`;
}
function drawer(state) {
  const scopeStart=state.drawerScope==='labs'?CORE_APP_COUNT:0, scopeEnd=state.drawerScope==='labs'?APP_DEFS.length:CORE_APP_COUNT, scopeCount=scopeEnd-scopeStart;
  let local=state.drawerIndex-scopeStart;if(local<0||local>=scopeCount)local=0;const page=Math.floor(local/4),start=scopeStart+page*4,items=APP_DEFS.slice(start,Math.min(start+4,scopeEnd));
  return `<main id="content" class="content drawer-content"><div class="drawer-toolbar"><button class="scope-tab${selected(state.drawerScope==='core')}" data-action="drawer-core" data-interactive="1">CORE 11</button><button class="scope-tab${selected(state.drawerScope==='labs')}" data-action="drawer-labs" data-interactive="1">LABS 5</button><span>${page+1}/${Math.ceil(scopeCount/4)}</span></div><div class="drawer-list">${items.map((item,o)=>{const i=start+o;return `<button class="drawer-row${selected(i===state.drawerIndex)} accent-${item.accent}" data-open-screen="${i}" data-interactive="1"><span class="drawer-index">${i<CORE_APP_COUNT?String(i+1).padStart(2,'0'):'L'+(i-CORE_APP_COUNT+1)}</span><span class="drawer-name">${esc(item.title)}</span><span class="mini-fidelity">${item.fidelity[0]}</span><span>›</span></button>`}).join('')}</div><div class="drawer-help">wheel chooses · hold side/open selects · CORE matches lilLED composition</div></main>`;
}

function motionBadge(state) { const m=state.motion; return `<span class="motion-badge ${m.fresh&&m.validGravity?'good':'warn'}">${m.source} ${m.fresh?`${m.pitch.toFixed(0)}°/${m.roll.toFixed(0)}°`:'STALE'}</span>`; }
function focusChip(label, value, focus, current) { return `<button class="focus-chip${selected(current===focus)}" data-focus="${focus}" data-interactive="1"><span>${label}</span><b>${esc(value)}</b></button>`; }

function rain(state) {
  const r=state.rain;
  return `<main id="content" class="content rain-content"><div class="screen-subhead"><span>RAIN PROBLEM</span><b>${esc(r.imuStatus)}</b></div><section class="rain-status"><span>H ${r.hits}</span><span>M ${r.misses}</span><span>P ${r.predicted}</span><b>W ${Math.round(r.effectiveWind)}</b></section><canvas id="rainCanvas" class="viz-canvas rain-canvas" width="220" height="119" data-interactive="1"></canvas><div class="focus-row">${focusChip('WIND',Math.round(r.manualWind),'WIND',r.focus)}${focusChip('RATE',`${r.spawnRate}/s`,'RATE',r.focus)}${focusChip('FALL',Math.round(r.fallSpeed),'FALL',r.focus)}${focusChip('TARGET',Math.round(r.targetSpeed),'TARGET',r.focus)}</div><div class="mini-actions">${button(r.windMode==='IMU'?'IMU→MANUAL':'MANUAL→IMU','rain-mode')}${button(r.predictor,'rain-predictor')}${button('RESET','rain-reset')}</div><div class="hint">tilt X→wind/target · pitch→drop speed · wheel edits focused baseline</div></main>`;
}
function hsv(state) {
  const h=state.hsv;
  return `<main id="content" class="content hsv-content"><div class="screen-subhead"><span>HSV CONE SLICER</span><b>${h.imuPlane?esc(h.imuStatus):'MANUAL PLANE'}</b></div><div class="hsv-layout"><div class="cone-wrap"><canvas id="hsvCone" width="105" height="133" data-interactive="1"></canvas><small>drag cone: orbit</small></div><div class="section-wrap"><div class="section-pill">${esc(h.preset)}</div><div class="hsv-values">T ${h.tilt.toFixed(1)}° · S ${Math.round(h.spin)}°</div><div id="hsvPad" class="hsv-section" data-interactive="1" style="--h:${h.selectedHue};--s:${h.selectedSaturation};--v:${h.selectedValue}"><span class="sample-dot"></span></div><div>OFF ${h.offset.toFixed(2)}</div></div></div><div class="focus-row hsv-focus">${focusChip('OFFSET',h.offset.toFixed(2),'OFFSET',h.focus)}${focusChip('TILT',`${h.manualTilt.toFixed(0)}°`,'TILT',h.focus)}${focusChip('SPIN',`${h.manualSpin.toFixed(0)}°`,'SPIN',h.focus)}</div><div class="mini-actions">${button(h.imuPlane?'IMU ON':'IMU OFF','hsv-imu')}${button('PRESET','hsv-preset')}${button('UNDO','hsv-undo')}${button('CLEAR','hsv-clear')}</div><div class="hint">IMU plane uses calibrated gravity · touch section samples · wheel fine-trims focus</div></main>`;
}
function aem(state) {
  const a=state.aem;
  return `<main id="content" class="content aem-content"><div class="screen-subhead"><span>AEM ELECTROLYZER</span><b>${a.imuControl?esc(a.imuStatus):'BASELINE'}</b></div><section class="aem-summary"><b>V${a.voltage.toFixed(2)}</b><b>J${a.currentDensity.toFixed(2)}</b><b>H₂ ${a.h2Rate.toFixed(2)}</b></section><div id="aemStack" class="aem-visual" data-interactive="1" style="--load:${a.load}%"><div class="aem-side cathode"><strong>CATHODE</strong><span>H₂O ${Math.round(a.effectiveWater??a.water)}%</span><span>H₂⌃</span></div><div class="aem-membrane"><strong>AEM</strong><span>${a.membrane}%</span><i></i></div><div class="aem-side anode"><strong>ANODE</strong><span>O₂⌃</span><span>${a.efficiency}% eff</span></div><div class="aem-loadbar"></div></div><div class="focus-row">${focusChip('LOAD',`${a.baselineLoad}%`,'LOAD',a.focus)}${focusChip('WATER',`${a.water}%`,'WATER',a.focus)}${focusChip('EFF',`${a.efficiency}%`,'EFF',a.focus)}${focusChip('MEM',`${a.membrane}%`,'MEM',a.focus)}</div><div class="mini-actions">${button(a.driver,'aem-driver')}${button(a.imuControl?'IMU ON':'IMU OFF','aem-imu')}${button(a.degas?'STOP DEGAS':'DEGAS','aem-degas')}</div><div class="hint">tilt modifies effective load/water only; shake triggers temporary degas</div></main>`;
}
function synth(state) {
  const s=state.synth,x=Math.round(s.padX*100),y=Math.round(s.padY*100);
  if(s.page==='map') return `<main id="content" class="content synth-content"><div class="screen-subhead"><span>SYNTH / MAPPING</span><b>${esc(s.preset)}</b></div><div class="mapping-grid">${focusChip('X MAP',s.mapX,'MAPX',s.focus)}${focusChip('Y MAP',s.mapY,'MAPY',s.focus)}${focusChip('ARP DIR',s.arpDirection,'ARPDIR',s.focus)}${focusChip('ARP SPAN',s.arpSpan,'ARPSPAN',s.focus)}${focusChip('ARP RATE',s.arpRate,'ARPRATE',s.focus)}${focusChip('TEMPO',s.tempo,'TEMPO',s.focus)}</div><div class="mini-actions">${button('PERFORM','synth-perform')}${button(s.imuMotion?'MOTION ON':'MOTION OFF','synth-imu')}${button('SOUND','synth-sound')}</div><div class="hint">tilt modulates arp/effects; wheel edits selected mapping</div></main>`;
  if(s.page==='sound') return `<main id="content" class="content synth-content"><div class="screen-subhead"><span>SYNTH / SOUND</span><b>${esc(s.waveform)}</b></div><div class="mapping-grid">${focusChip('CUTOFF',Math.round(s.cutoff),'CUTOFF',s.focus)}${focusChip('RESON',s.resonance.toFixed(2),'RESONANCE',s.focus)}${focusChip('DELAY',s.baseDelay.toFixed(2),'DELAY',s.focus)}${focusChip('REVERB',s.baseReverb.toFixed(2),'REVERB',s.focus)}${focusChip('VOL',`${s.volume}%`,'VOLUME',s.focus)}${focusChip('TRANS',s.transpose,'TRANSPOSE',s.focus)}</div><div class="mini-actions">${button('WAVE','synth-wave')}${button('PERFORM','synth-perform')}${button('MAPPING','synth-map')}</div></main>`;
  return `<main id="content" class="content synth-content"><div class="screen-subhead"><span>SYNTH / PERFORM</span><b>${s.active?'PLAYING':esc(s.imuStatus)}</b></div><div id="synthPad" class="xy-pad synth-pad" data-interactive="1" style="--x:${x}%;--y:${100-y}%"><div class="xy-grid"></div><div class="xy-cross"></div><div class="xy-dot"></div><span class="pad-axis x-axis">X ${esc(s.mapX)}</span><span class="pad-axis y-axis">Y ${esc(s.mapY)}</span></div><section class="synth-status"><div><b>${s.waveform} · ${s.tempo} BPM</b><span>${s.pitchFloor}–${s.pitchCeiling} MIDI</span></div><div><span>DLY ${Math.round(s.delay*100)}%</span><span>RV ${Math.round(s.reverb*100)}%</span><span>LPF ${Math.round(s.cutoff)}</span></div><div><span>ARP ${s.arpDirection} ×${s.arpSpan}</span>${motionBadge(state)}</div></section><div class="mini-actions">${button('MAPPING','synth-map')}${button('SOUND','synth-sound')}${button(s.muted?'UNMUTE':'MUTE','synth-mute')}</div></main>`;
}
function percussion(state) {
  const p=state.percussion;
  if(p.page==='pattern') return `<main id="content" class="content percussion-content"><div class="screen-subhead"><span>PERC / PATTERN INSPECTOR</span><b>R1 EXTENSION</b></div><div class="pattern16">${PERCUSSION_VOICES.map(v=>`<div class="pattern-row"><span>${v[0].toUpperCase()}</span>${p.pattern[v].map((on,i)=>`<button data-perc-step="${v}:${i}" data-interactive="1" class="pstep${on?' on':''}${i===p.currentStep?' playhead':''}"></button>`).join('')}</div>`).join('')}</div><div class="pattern-legend"><span>${p.kit}</span><span>E${p.energy}</span><span>G${p.groove}</span><span>${p.bpm} BPM</span></div>${button('BACK TO WHOLE-KIT XY','perc-view','class="wide-button"')}<div class="hint">source patterns retained; inspector is intentionally labeled an R1 extension</div></main>`;
  const x=Math.round(p.padX*100),y=Math.round(p.padY*100);
  return `<main id="content" class="content percussion-content"><div class="screen-subhead"><span>PERCUSSION / WHOLE KIT</span><b>${p.playing?'LOOPING':'READY'}</b></div><div id="percussionPad" class="xy-pad percussion-pad" data-interactive="1" style="--x:${x}%;--y:${y}%"><div class="xy-grid four"></div><div class="xy-cross"></div><div class="xy-dot"></div><span class="axis-groove">GROOVE</span><span class="axis-energy">ENERGY →</span></div><section class="perc-status"><b>${p.kit} / ${esc(p.variationArmed||p.variation)}</b><span>E ${p.energy}/4 · G ${p.groove}/4 · ${p.bpm} BPM</span><span class="${p.contact?'green':p.graceDeadline>Date.now()?'amber':'muted'}">${p.contact?'CONTACT':p.graceDeadline>Date.now()?'650ms RETOUCH WINDOW':p.stopAtBoundary?'STOP AT LOOP BOUNDARY':'TOUCH TO START / RETOUCH FOR VARIATION'}</span><span>FX D${Math.round(p.delay*100)} R${Math.round(p.reverb*100)} · ${esc(p.imuStatus)}</span></section><div class="mini-actions">${button('PATTERN','perc-view')}${button(p.motionFx?'MOTION FX':'FX OFF','perc-motion')}${button('KIT','perc-kit')}</div></main>`;
}
function recorder(state, platform) {
  const r=state.recorder;const status=r.error||(r.state==='recording'?`${r.seconds.toFixed(1)} s`:r.hasClip?`REVIEW ${r.duration.toFixed(1)}s`:'READY');
  return `<main id="content" class="content recorder-content"><div class="screen-subhead"><span>RECORDER</span><b>${platform.capabilities.microphone?'MIC':'MIC ?'}</b></div><button class="record-button${active(r.state==='recording')}" data-action="record" data-interactive="1">${r.state==='recording'?'STOP':r.hasClip?'PLAY':'RECORD'}</button><div class="record-status${r.error?' red':''}">${esc(status)}</div>${r.hasClip?`<div class="seek-row"><button data-action="record-back" data-interactive="1">−5s</button><input id="recordSeek" data-interactive="1" type="range" min="0" max="${Math.max(.1,r.duration)}" step="0.1" value="${Math.min(r.position,r.duration)}"><button data-action="record-forward" data-interactive="1">+5s</button></div><div class="rec-review"><button data-action="record-replay" data-interactive="1">PLAY</button><button data-action="record-save" data-interactive="1">SAVE</button><button data-action="record-discard" data-interactive="1">DISCARD</button></div>${r.saved?button('SHARE TO COMMUNICATIONS','record-share','class="wide-button"'):''}`:`<div class="rec-note">Capture stays navigation-guarded until Stop. Review supports seek, Save/Discard, then optional message sharing.</div>`}<div class="hint">real mic when exposed · media stored in IndexedDB/local repository</div></main>`;
}
function udaq(state) {
  const u=state.udaq;
  return `<main id="content" class="content udaq-content"><div class="screen-subhead"><span>uDAQ ${u.view}</span><b class="${u.inputSource==='DEMO'?'source-demo':''}">${u.sourceFresh?'LIVE':u.sourceAvailable?'STALE':'WAIT'} ${u.source}</b></div><div class="daq-meta"><span>AX ${u.sourceAvailable?u.x.toFixed(2):'—'}</span><span>AY ${u.sourceAvailable?u.y.toFixed(2):'—'}</span><span>AZ ${u.sourceAvailable?u.z.toFixed(2):'—'}</span><span>|A| ${u.sourceAvailable?u.magnitude.toFixed(2):'—'}</span></div><canvas id="daqCanvas" class="viz-canvas daq-canvas" width="220" height="112" data-interactive="1"></canvas><button class="daq-footer" data-action="udaq-run" data-interactive="1"><span>${u.running?'RUN':'PAUSE'}</span><span>${u.sampleRate} Hz</span><span>${u.history.length}/300</span><span>${u.view}</span></button><div class="mini-actions">${button('RATE','udaq-rate')}${button(u.inputSource==='DEMO'?'DEMO ON':'DEMO OFF','udaq-source')}${button('CENTER','udaq-zero')}${button('CSV','udaq-export')}</div><div class="hint">300-sample ring · wheel changes trace · run panel toggles capture</div></main>`;
}
function settings(state) {
  const s=state.settings,m=state.motion;
  if(s.page===2) return `<main id="content" class="content settings-content motion-lab"><div class="settings-title"><span>MOTION LAB</span><span>PAGE 3/3</span></div><div class="motion-table"><span>RAW</span><b>${m.rawX.toFixed(2)} ${m.rawY.toFixed(2)} ${m.rawZ.toFixed(2)}</b><span>LOGICAL</span><b>${m.x.toFixed(2)} ${m.y.toFixed(2)} ${m.z.toFixed(2)}</b><span>PITCH</span><b>${m.pitch.toFixed(1)}°</b><span>ROLL</span><b>${m.roll.toFixed(1)}°</b><span>|G| / JERK</span><b>${m.magnitude.toFixed(2)} / ${m.jerk.toFixed(2)}</b><span>STATUS</span><b>${m.fresh?(m.validGravity?'VALID':'MOVE SLOW'):'STALE'}</b></div><div class="mini-actions">${button('CENTER DEVICE','settings-center')}${button('RESET PATTERN','settings-pattern-reset')}${button('INTRO','settings-intro')}</div><div class="hint">center establishes neutral pitch/roll; calibration is shared by every motion app</div></main>`;
  const pages=[[['DISPLAY',`BRIGHT ${s.brightness} · ${s.orientation}`,0],['SCREEN SLEEP',s.screenIdle,1],['TOUCH INPUT',`${s.touchDown}↓ ${s.touchUp}↑ DROP ${s.touchDrop}`,2],['MOTION ZERO',s.imuZero,3]],[['TEXT',s.textSize,0],['MESSAGE SOUND',s.messageSound?'ON':'OFF',1],['REDUCED MOTION',s.reducedMotion?'ON':'OFF',2],['DIAGNOSTICS',s.diagnostics?'ON':'OFF',3]]],rows=pages[s.page%2];
  return `<main id="content" class="content settings-content"><div class="settings-title"><span>SETTINGS</span><span>PAGE ${s.page+1}/3</span></div>${rows.map(([l,v,f])=>`<button class="setting-card${selected(s.focus===f)}" data-setting-focus="${f}" data-interactive="1"><b>${l}</b><span>${esc(v)}</span></button>`).join('')}<div class="hint">wheel adjusts selected row · primary cycles pages · page 3 is Motion Lab</div></main>`;
}
function patternLock(appId, state, title) {
  const lockedOut=state.lockoutUntil>Date.now();
  return `<main id="content" class="content lock-content"><div class="lock-head"><strong>${esc(title)}</strong><span>${lockedOut?'LOCKED OUT':'DRAW PATTERN'}</span></div><div class="pattern-grid" data-pattern-app="${appId}" data-interactive="1">${Array.from({length:9},(_,i)=>`<div class="pattern-dot" data-pattern-dot="${i}"><i></i></div>`).join('')}</div><div class="lock-note">${lockedOut?'5 minute lockout active':'shared Settings credential · 3 failed attempts lock for 5 min'}</div></main>`;
}
function transfer(state) {
  const t=state.transfer;if(!t.unlocked)return patternLock('transfer',t,'TRANSFER LOCK');
  if(t.browserPage==='browser') return `<main id="content" class="content transfer-content"><div class="screen-subhead"><span>TRANSFER / FILES</span><b>LOCAL</b></div><div class="file-list">${t.files.slice(0,4).map((f,i)=>`<button class="file-row${selected(i===t.selected)}" data-file-index="${i}" data-interactive="1"><b>${esc(f.name)}</b><small>${esc(f.type)} · ${esc(f.size)}</small></button>`).join('')}</div><div class="mini-actions">${button('OPEN','transfer-preview')}${button('HOME','transfer-home')}${button('EXPORT','transfer-export')}</div></main>`;
  if(t.browserPage==='preview'){const f=t.files[t.selected]||t.files[0];return `<main id="content" class="content transfer-content"><div class="screen-subhead"><span>PREVIEW</span><b>${esc(f.type)}</b></div><section class="preview-card"><b>${esc(f.name)}</b><span>${esc(f.preview||'No preview')}</span><small>${esc(f.size)}</small></section><div class="mini-actions">${button('BACK','transfer-browser')}${button('EXPORT','transfer-export')}${button('LOCK','transfer-lock')}</div><div class="hint">text/image/audio previews use Creation-owned media; no SD/USB claim</div></main>`;}
  if(t.browserPage==='wireless') return `<main id="content" class="content transfer-content"><div class="screen-subhead"><span>TRANSFER / HOST BRIDGE</span><b>${esc(t.wireless)}</b></div><section class="transfer-card"><b>${esc(t.transferState)}</b><span>optional host WebSocket/HTTP transport</span><div class="progress"><i style="width:${t.progress}%"></i></div></section><div class="mini-actions">${button(t.wireless==='ON'?'STOP':'ENABLE','transfer-toggle-wireless')}${button('HOME','transfer-home')}${button('LOCK','transfer-lock')}</div><div class="hint">wireless is never labeled successful until an external provider acknowledges it</div></main>`;
  return `<main id="content" class="content transfer-content"><div class="screen-subhead"><span>TRANSFER</span><b>UNLOCKED</b></div><div class="tile-grid"><button data-action="transfer-browser" data-interactive="1"><b>FILES</b><span>browse / preview / playback</span></button><button data-action="transfer-wireless" data-interactive="1"><b>HOST</b><span>optional external transfer</span></button><button data-action="transfer-export" data-interactive="1"><b>EXPORT</b><span>state JSON</span></button><button data-action="transfer-lock" data-interactive="1"><b>LOCK</b><span>re-lock now</span></button></div><div class="hint">leaving app re-locks by policy</div></main>`;
}
function communications(state, platform) {
  const c=state.communications;if(!c.unlocked)return patternLock('communications',c,'COMMUNICATIONS LOCK');
  if(c.section==='compose') return `<main id="content" class="content communications-content"><div class="screen-subhead"><span>COMPOSE</span><b>${c.draft.length}/200</b></div><div class="draft-box">${esc(c.draft)||'<span class="muted">EMPTY DRAFT</span>'}</div><div class="char-wheel"><button data-action="comm-char-back" data-interactive="1">⌫</button><b>${esc(' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_'[c.charIndex])||'␠'}</b><button data-action="comm-char-add" data-interactive="1">ADD</button></div><div class="compose-actions">${button('SAVE LOCAL','comm-save-local')}${button('REVIEW','comm-review')}</div><div class="hint">physical wheel chooses character · touch ADD commits · unknown remote state is never delivery</div></main>`;
  if(c.section==='journal') return `<main id="content" class="content communications-content"><div class="screen-subhead"><span>CHAT HISTORY</span><b>${c.journal.length}</b></div><div class="journal-list">${c.journal.slice(-4).reverse().map(m=>`<div class="journal-row"><small>${esc(m.from)} · ${esc(m.time)} · ${esc(m.receipt||'LOCAL')}</small><span>${esc(m.text)}</span></div>`).join('')}</div><div class="mini-actions">${button('HOME','comm-home')}${button('NEW','comm-compose')}${button('CLEAR','comm-clear')}</div></main>`;
  if(c.section==='review') return `<main id="content" class="content communications-content"><div class="screen-subhead"><span>DRAFT REVIEW</span><b>${esc(c.destination)}</b></div><div class="draft-box">${esc(c.draft)||'EMPTY'}</div><section class="bridge-card"><small>TRANSPORT</small><b>${esc(c.bridge)}</b><span>${esc(c.lastBridge)}</span></section><div class="mini-actions">${button('LOCAL SAVE','comm-save-local')}${button('RABBIT TEST','comm-rabbit-ping')}${button('EDIT','comm-compose')}</div></main>`;
  return `<main id="content" class="content communications-content"><div class="screen-subhead"><span>MESSAGING</span><b>UNLOCKED</b></div><div class="message-home"><button data-action="comm-compose" data-interactive="1"><b>NEW TEXT</b><span>CharacterWheel compose</span></button><button data-action="comm-journal" data-interactive="1"><b>HISTORY</b><span>${c.journal.length} records</span></button><button data-action="comm-quick" data-interactive="1"><b>QUICK</b><span>four-choice content</span></button><button data-action="comm-lock" data-interactive="1"><b>LOCK</b><span>shared pattern</span></button></div><section class="bridge-card"><small>RABBIT BRIDGE</small><b>${platform.capabilities.pluginMessages?'AVAILABLE':'OFFLINE'}</b><span>${esc(c.lastBridge)}</span></section><div class="hint">Recorder voice assets can be staged here after Save</div></main>`;
}
function whofi(state) {
  const w=state.whofi;let body='';
  if(w.page==='home') body=`<section class="who-card"><small>LIVE</small><b>${w.running?`${w.provider} ${w.csiRate} pkt/s`:'STOPPED'}</b><span>${w.configured?'PROFILE CONFIGURED':'SETUP REQUIRED / SIM ALLOWED'}</span></section><div class="who-metrics"><span>RSSI <b>${w.running?w.rssi+' dBm':'—'}</b></span><span>CHANNEL <b>${w.running?w.channel:'—'}</b></span><span>DROPS <b>${w.drops}</b></span><span>VIEW <b>${w.frozen?'FROZEN':'LIVE'}</b></span></div><div class="mini-actions">${button('MENU','whofi-menu')}${button(w.running?'STOP':'START','whofi-toggle')}</div>`;
  else if(w.page==='menu') body=`<div class="tile-grid"><button data-whofi-page="view" data-interactive="1"><b>VIEW</b><span>plot/freeze/gain</span></button><button data-whofi-page="session" data-interactive="1"><b>CAPTURE</b><span>stream contract</span></button><button data-whofi-page="tools" data-interactive="1"><b>TOOLS</b><span>Wi-Fi/signal/display/help</span></button><button data-whofi-page="home" data-interactive="1"><b>LIVE</b><span>return</span></button></div>`;
  else if(w.page==='view') body=`<canvas id="whofiCanvas" class="who-signal" width="220" height="117"></canvas><div class="signal-footer"><span>${w.frozen?'FROZEN':'LIVE'}</span><span>${esc(w.plot)}</span><span>${w.fixedSpan?'FIXED':'AUTO'}</span></div><div class="mini-actions">${button(w.frozen?'RESUME':'FREEZE','whofi-freeze')}${button('PLOT','whofi-plot')}${button(w.fixedSpan?'FIXED':'AUTO','whofi-gain')}${button('CLEAR','whofi-clear')}</div>`;
  else if(w.page==='session') body=`<section class="who-session"><small>CAPTURE</small><b>${w.rawStream?'REMOTE STREAM ON':'REMOTE STREAM OFF'}</b><span>Records ${w.records}</span><span>USB/PC file is never implied by local state.</span></section><div class="mini-actions">${button(w.rawStream?'STREAM OFF':'STREAM ON','whofi-raw')}${button('MENU','whofi-menu')}</div>`;
  else if(w.page==='tools') body=`<div class="tile-grid"><button data-whofi-page="connection" data-interactive="1"><b>WI-FI</b><span>provider/profile</span></button><button data-whofi-page="signal" data-interactive="1"><b>SIGNAL</b><span>counters/details</span></button><button data-whofi-page="settings" data-interactive="1"><b>DISPLAY</b><span>brightness/cues</span></button><button data-whofi-page="help" data-interactive="1"><b>HELP</b><span>truth boundary</span></button></div>`;
  else if(w.page==='connection') body=`<section class="who-card"><small>CONNECTION</small><b>${esc(w.provider)}</b><span>Native R1 raw CSI unavailable. SIM or an explicit remote WebSocket provider may feed this model.</span></section><div class="mini-actions">${button('SIM','whofi-provider-sim')}${button('TOOLS','whofi-tools')}</div>`;
  else if(w.page==='signal') body=`<section class="who-card"><small>SIGNAL DETAILS</small><b>${w.rssi} dBm · CH ${w.channel}</b><span>rejects ${w.rejects} · drops ${w.drops} · records ${w.records}</span></section><div class="mini-actions">${button('ADVANCED','whofi-advanced')}${button('TOOLS','whofi-tools')}</div>`;
  else if(w.page==='settings') body=`<div class="who-settings"><b>DISPLAY / CUES</b><span>Brightness ${w.brightness}/255</span><div class="two-buttons">${button('DIMMER','whofi-dimmer')}${button('BRIGHTER','whofi-brighter')}</div><span>Cue level ${w.cueLevel}%</span><div class="two-buttons">${button('CUE −','whofi-cue-down')}${button('CUE +','whofi-cue-up')}</div>${button(w.cues?'CUES ON':'CUES OFF','whofi-cues','class="wide-button"')}</div>`;
  else if(w.page==='advanced') body=`<section class="who-card"><small>ADVANCED</small><b>PROVIDER ${esc(w.provider)}</b><span>raw stream ${w.rawStream?'ON':'OFF'} · span ${w.span} · detail page ${w.detailPage}</span></section><div class="mini-actions">${button('NEXT DETAIL','whofi-detail')}${button('SIGNAL','whofi-signal')}</div>`;
  else body=`<section class="who-card"><small>HELP</small><b>EXPERIMENTAL RELATIVE CSI</b><span>Does not identify a person, locate an object, count occupancy, or provide calibrated motion confidence. SIM remains visibly marked.</span></section><div class="mini-actions">${button('TOOLS','whofi-tools')}</div>`;
  return `<main id="content" class="content whofi-content"><div class="screen-subhead"><span>WHOFI</span><b>${esc(w.provider)} ${w.running?'LIVE':'IDLE'}</b></div>${body}<div class="hint">full Live/Menu/View/Capture/Tools flow; provider is separated from presentation</div></main>`;
}
function lilmidi(state) {
  const m=state.lilmidi,x=Math.round(m.padX*100),y=Math.round(m.padY*100);
  if(m.page==='map') return `<main id="content" class="content midi-content"><div class="screen-subhead"><span>lilMIDI / AXES</span><b>REV ${m.revision}</b></div><div class="mapping-grid">${focusChip('X MAP',m.mapX,'MAPX',m.focus)}${focusChip('Y MAP',m.mapY,'MAPY',m.focus)}${focusChip('CHANNEL',m.channel,'CHANNEL',m.focus)}${focusChip('GROUP',m.group,'GROUP',m.focus)}${focusChip('ROUTE',m.route,'ROUTE',m.focus)}${focusChip('SCENE',m.scene,'SCENE',m.focus)}</div><div class="mini-actions">${button('REVIEW','midi-review')}${button('PERFORM','midi-perform')}</div></main>`;
  if(m.page==='scenes') return `<main id="content" class="content midi-content"><div class="screen-subhead"><span>lilMIDI / SCENES</span><b>${esc(m.scene)}</b></div><div class="scene-grid">${m.scenes.map(s=>`<button data-midi-scene="${esc(s)}" data-interactive="1" class="${s===m.scene?'selected':''}">${esc(s)}</button>`).join('')}</div><div class="mini-actions">${button('PERFORM','midi-perform')}${button('AXES','midi-map')}</div></main>`;
  if(m.page==='review') return `<main id="content" class="content midi-content"><div class="screen-subhead"><span>lilMIDI / REVIEW</span><b>${m.draftDirty?'DRAFT':'CLEAN'}</b></div><section class="preview-card"><b>CH ${m.channel} · ${esc(m.route)} · ${esc(m.group)}</b><span>X ${esc(m.mapX)} / Y ${esc(m.mapY)}</span><small>revision ${m.revision} · ack ${m.ackRevision}</small></section><div class="mini-actions">${button('APPLY','midi-apply')}${button('DISCARD','midi-discard')}${button('AXES','midi-map')}</div></main>`;
  return `<main id="content" class="content midi-content"><div class="screen-subhead"><span>lilMIDI</span><b>${esc(m.bridge)}</b></div><div id="midiPad" class="xy-pad midi-pad" data-interactive="1" style="--x:${x}%;--y:${100-y}%"><div class="xy-grid"></div><div class="xy-cross"></div><div class="xy-dot"></div></div><section class="midi-map"><span>SCENE <b>${esc(m.scene)}</b></span><span>CH <b>${m.channel}</b></span><span>X <b>${esc(m.mapX)}=${m.valueX}</b></span><span>Y <b>${esc(m.mapY)}=${m.valueY}</b></span></section><div class="mini-actions">${button('AXES','midi-map')}${button('SCENES','midi-scenes')}</div><div class="hint">host bridge may emit real MIDI/OSC; direct USB MIDI is not claimed</div></main>`;
}
function particles(state) {
  const p=state.particles;
  return `<main id="content" class="content particles-content"><div class="screen-subhead"><span>PARTICLES</span><b>${p.paused?'PAUSED':esc(p.preset)}</b></div><canvas id="particlesCanvas" class="particles-canvas" width="220" height="135" data-interactive="1"></canvas><div class="focus-row">${focusChip('ATTR',p.attraction.toFixed(2),'ATTRACTION',p.focus)}${focusChip('ORBIT',p.orbitRadius,'ORBIT',p.focus)}${focusChip('GRAV',p.gravity.toFixed(2),'GRAVITY',p.focus)}${focusChip('COUNT',p.count,'COUNT',p.focus)}</div><div class="mini-actions">${button(p.paused?'RESUME':'PAUSE','particles-pause')}${button('RESET','particles-reset')}${button('PRESET','particles-preset')}${button(p.grid?'GRID ON':'GRID OFF','particles-grid')}</div><div class="hint">drag moves orbit target · wheel edits focused physics parameter</div></main>`;
}
function notebook(state) {
  const n=state.notebook;
  if(n.page==='timer') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>TIMER</span><b>${n.timerRunning?'RUN':'PAUSE'}</b></div><div class="big-time">${Math.floor(n.timerRemaining/60).toString().padStart(2,'0')}:${Math.floor(n.timerRemaining%60).toString().padStart(2,'0')}</div><div class="mini-actions">${button(n.timerRunning?'PAUSE':'START','notebook-timer-toggle')}${button('RESET','notebook-timer-reset')}${button('HOME','notebook-home')}</div></main>`;
  if(n.page==='stopwatch') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>STOPWATCH</span><b>${n.stopwatchRunning?'RUN':'PAUSE'}</b></div><div class="big-time">${(n.stopwatchMs/1000).toFixed(1)}s</div><div class="mini-actions">${button(n.stopwatchRunning?'PAUSE':'START','notebook-stopwatch-toggle')}${button('RESET','notebook-stopwatch-reset')}${button('HOME','notebook-home')}</div></main>`;
  if(n.page==='calendar') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>CALENDAR</span><b>${new Date().getFullYear()}</b></div><div class="calendar-card">${new Date(Date.now()+n.calendarOffset*86400000).toDateString()}</div><div class="mini-actions">${button('HOME','notebook-home')}</div></main>`;
  if(n.page==='weather') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>WEATHER</span><b>PROVIDER</b></div><section class="preview-card"><b>${esc(n.weather)}</b><span>No fabricated forecast. Connect a weather provider in a future optional integration.</span></section><div class="mini-actions">${button('HOME','notebook-home')}</div></main>`;
  if(n.page==='calculator') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>CALCULATOR</span><b>LOCAL</b></div><div class="calc-display">${esc(n.calc)}</div><div class="mini-actions">${button('CLEAR','notebook-calc-clear')}${button('+1','notebook-calc-plus')}${button('HOME','notebook-home')}</div></main>`;
  if(n.page==='ruler') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>RULER</span><b>${n.rulerMm} mm</b></div><div class="ruler"><i></i><i></i><i></i><i></i><i></i><span>software scale · physical calibration required</span></div><div class="mini-actions">${button('HOME','notebook-home')}</div></main>`;
  if(n.page==='settings') return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>NOTEBOOK SETTINGS</span><b>${esc(n.accent)}</b></div><div class="tile-grid"><button data-action="notebook-accent" data-interactive="1"><b>ACCENT</b><span>${esc(n.accent)}</span></button><button data-action="notebook-dim" data-interactive="1"><b>IDLE DIM</b><span>${n.idleDimming?'ON':'OFF'}</span></button></div><div class="mini-actions">${button('HOME','notebook-home')}</div></main>`;
  return `<main id="content" class="content notebook-content"><div class="screen-subhead"><span>NOTEBOOK</span><b>7 UTILITIES</b></div><div class="notebook-grid seven">${[['CALENDAR','calendar'],['WEATHER','weather'],['TIMER','timer'],['STOPWATCH','stopwatch'],['CALCULATOR','calculator'],['RULER','ruler'],['SETTINGS','settings']].map(([l,p],i)=>`<button class="${i===n.selected?'selected':''}" data-notebook-page="${p}" data-interactive="1"><b>${l}</b></button>`).join('')}</div></main>`;
}
function power(state) { const p=state.power,level=p.level==null?'—':`${Math.round(p.level*100)}%`;return `<main id="content" class="content power-content"><div class="screen-subhead"><span>POWER</span><b>${p.supported?'BATTERY API':'UNAVAILABLE'}</b></div><div class="battery-gauge"><i style="width:${p.level==null?0:Math.round(p.level*100)}%"></i><span>${level}</span></div><section class="power-card"><span>CHARGING <b>${p.charging==null?'—':p.charging?'YES':'NO'}</b></span><span>CHARGE TIME <b>${Number.isFinite(p.chargingTime)?Math.round(p.chargingTime/60)+'m':'—'}</b></span><span>DISCHARGE <b>${Number.isFinite(p.dischargingTime)?Math.round(p.dischargingTime/60)+'m':'—'}</b></span></section><canvas id="powerCanvas" class="power-canvas" width="220" height="60"></canvas><div class="hint">real Battery API only; unavailable is shown explicitly</div></main>`; }
function camera(state, platform) {
  const c=state.camera;
  return `<main id="content" class="content camera-content"><div class="screen-subhead"><span>CAMERA</span><b>${c.state.toUpperCase()}</b></div><div class="camera-frame">${c.state==='live'?'<video id="cameraVideo" autoplay playsinline muted></video>':`<div class="camera-placeholder">${platform.capabilities.camera?'START CAMERA':'CAMERA API UNAVAILABLE'}</div>`}</div><div class="mini-actions">${button(c.state==='live'?'STOP':'START','camera-toggle')}${button('FLIP','camera-flip')}${button('SNAP','camera-snap',c.state==='live'?'':'disabled')}${c.dirty?button('SAVE','camera-save'):''}</div><div class="hint">R1 browser camera extension; saved captures use local media repository</div></main>`;
}

const renderers={rain,hsv,aem,synth,percussion,recorder,udaq,settings,transfer,communications,whofi,lilmidi,particles,notebook,power,camera};
export function render(state, platform) {
  const app=currentApp(state),body=state.drawerOpen?drawer(state):(renderers[app.id]?.(state,platform)||'<main class="content">Unavailable</main>');
  const status=state.statusMessage&&state.statusUntil>Date.now()?`<div class="toast">${esc(state.statusMessage)}</div>`:'';
  const diag=state.settings.diagnostics?`<div class="diag-badge">${esc(platform.environmentLabel())} · ${esc(app.id)} · ${esc(app.fidelity)} · ${state.motion.source}</div>`:'';
  return `${header(state,platform)}${body}${footer(state)}${status}${diag}`;
}
